### ISSUE TITLE
quadrics visualization 

### ISSUE THREAD

**Issue by moshanATucsd** [tiev-tongji/quadric_slam#10]
Hi, 

after running `roslaunch object_slam object_slam_example.launch`, there's only camera pose in rviz, but no quadrics. Could you kindly advice how could we visualize the quadrics?

**Comment by JerryAIwei** [comment]
please run git reset --hard ca08b0a1512b35fd3e90bfebe1bd27cf7278097b, I think in this version you can see the quadrics in rviz.
